site_name: Tesserae API (Pre-Alpha!)
nav:
- 'Home': 'index.md'
- 'Getting Started':
    - 'Tutorial': 'getting-started/tutorial.md'
      # - 'CTS URNs': 'getting-started/cts-urns.md'
- 'Endpoints':
    - '/parallels/': 'endpoints/parallels.md'
    - '/parallels/&ltuuid&gt/': 'endpoints/parallels-uuid.md'
    - '/stopwords/': 'endpoints/stopwords.md'
    - '/stopwords/lists/': 'endpoints/stopwords-lists.md'
    - '/stopwords/lists/&lt;name&gt;/': 'endpoints/stopwords-lists-name.md'
    - '/texts/': 'endpoints/texts.md'
    - '/texts/&lt;object_id&gt;/': 'endpoints/texts-objid.md'
    - '/featuresets/': 'endpoints/featuresets.md'
      # - '/texts/&lt;cts_urn&gt;/units/': 'endpoints/texts-cts_urn-units.md'
- 'Details':
    - 'Cached Results': 'details/cached-results.md'
    - 'Scoring Methods': 'details/methods.md'
    - 'Units': 'details/units.md'
markdown_extensions:
    - toc:
        permalink: True
    - footnotes
    - mdx_math:
        enable_dollar_delimiter: True
    - smarty

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML']
